apiVersion: apps/v1
kind: Deployment
metadata:
  name: result-app-deploy
  labels:
    name: result-app-deploy
spec:
  template:
    metadata:
      name: result-app-pod
      labels:
        name: result-app
        app: demo-voting-app
    spec:
      containers:
       - name: result-app-container
         image: kodekloud/examplevotingapp_result:v1
         ports:
          - containerPort: 80
  replicas: 1
  selector:
    matchLabels:
      name: result-app
      app: demo-voting-app
