apiVersion: apps/v1
kind: Deployment
metadata:
  name: voting-app-deploy
  labels:
    name: voting-app-deploy
spec:
  template:
    metadata:
      name: voting-app-pod
      labels:
        name: voting-app
        app: demo-voting-app
    spec:
      containers:
       - name: voting-app-container
         image: kodekloud/examplevotingapp_vote:v1
         ports:
          - containerPort: 80
  replicas: 1
  selector:
    matchLabels:
      name: voting-app
      app: demo-voting-app
