apiVersion: v1
kind: Service
metadata:
  name: voting-app-service
spec:
  type: NodePort
  ports:
   - targetPort: 80
     port: 80
     nodePort: 30004
  selector:
    name: voting-app
    app: demo-voting-app
